name: superloja
description: Super loja online

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  flutter_bloc: ^5.0.1
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.1
  #funcional programming
  dartz: ^0.9.1
  # gerador de UUID
  uuid: ^2.1.0
  #data class e Sealed
  freezed_annotation: ^0.11.0
  flutter_icons: ^1.1.0
  #google signin
  google_sign_in: ^4.5.1
  #flusbar
  flushbar: ^1.10.4
  json_annotation: ^3.0.1
  carousel_pro: ^1.0.0
  carousel_slider: ^2.2.1
  flutter_staggered_grid_view: ^0.3.0
  transparent_image: ^1.0.0
  alphabet_list_scroll_view: ^1.0.6
  image_picker: ^0.6.7+4
  image_cropper: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  build_runner: 1.10.0
  injectable_generator: ^0.4.1
  freezed: ^0.11.2
  json_serializable: ^3.3.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
